# pylint: disable=no-member, invalid-name
"""create questions table

Revision ID: b9675e151c44
Revises: 6d5ff81312a6
Create Date: 2023-09-08 21:19:08.159753-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b9675e151c44'
down_revision: Union[str, None] = '6d5ff81312a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Create questions table
    :return: None
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('topic_id', sa.UUID(), nullable=False),
            sa.Column('text', sa.TEXT(), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Drop questions table
    :return: None
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
