# pylint: disable=no-member, invalid-name
"""add technology column to topics

Revision ID: cd0e59791550
Revises: bc36388929dc
Create Date: 2023-09-18 17:13:56.318008-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0e59791550'
down_revision: Union[str, None] = 'bc36388929dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Add technology column to topics
    :return: None
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('technology', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Drop technology column from topics
    :return: None
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'technology')
    # ### end Alembic commands ###
