services:
  app:
    build:
      context: ../
      dockerfile: ./infrastructure/dockerfile
      target: ${ENV}
    container_name: app
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    volumes:
      - ../main.py:/app/main.py
      - ../src:/app/src
    networks:
      - topic-trainer-network

  nginx:
    image: nginx:1.25.2-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - topic-trainer-network
networks:
  topic-trainer-network:
    driver: bridge
    name: topic-trainer-network
