FROM python:3.11.5-slim-bookworm as base

ARG UID
ARG GID
ARG UNAME
ARG GNAME

WORKDIR /app

RUN groupadd -f -g $GID $GNAME && \
    useradd -u $UID -g $GID $UNAME && \
    chown -R $UNAME:$GNAME /app

ENV PYTHONPATH=/app

COPY requirements/base.txt .

RUN pip install -r base.txt

COPY . .

EXPOSE 5000

FROM base as development

RUN pip install -r requirements/dev.txt

ENV PYLINTHOME=/app/.cache/pylint

CMD ["sh", "scripts/dev-start.sh"]

FROM base as production

CMD ["uwsgi", "--ini", "uwsgi.ini"]
